name: OtterAntiVPN
version: 1.3-Beta
author: aSwitch
description: A free adanced antivpn.
main: xyz.owltech.otter.OtterAntiVPN

permissions:
  otter.alerts:
    default: op
  otter.reload:
    default: op
  otter.command:
    default: op
  otter.purge:
    default: op
  otter.bypass:
    description: Bypass permission
commands:
  otter:
    description: Main command for OtterAntiVPN